name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libasound2-dev portaudio19-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create virtual environment
      run: |
        python3 -m venv AI-for-hairdessers/venv

    - name: Activate virtual environment
      run: |
        source AI-for-hairdessers/venv/bin/activate

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/AI-for-hairdessers
          git pull origin main
          pip install -r requirements.txt
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} > .env
          echo TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} >> .env
          echo TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} >> .env
          echo GGL_CAL_CREDS=${{ secrets.GGL_CAL_CREDS }} >> .env
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn

