name: Deploy to EC2

on:
  push:
    branches:
      - main
      - ismail/hosting

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libasound2-dev portaudio19-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/AI-for-hairdessers
          source venv/bin/activate
          pip install -r requirements.txt
          nohup gunicorn --bind 0.0.0.0:8000 wsgi:app &
