name: Deploy to EC2

on:
  push:
    branches:
      - main
      - skandere/s3-interactions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref_name }}  # Checkout the triggering branch

    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv  # Install python3-venv package

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/AI-for-hairdessers
          # Create virtual environment if it doesn't exist
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate  # Activate virtual environment
          git pull origin ${{ github.ref_name }}  # Pull changes from the triggering branch
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} > .env
          echo TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} >> .env
          echo TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} >> .env
          echo GGL_CAL_CREDS=${{ secrets.GGL_CAL_CREDS }} >> .env
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn



